name: Casino
version: '1.21.1'
main: net.hotamachisubaru.casino.Casino
api-version: '1.21'
depend:
  - Vault
author:
  Copyright (c) 2024 ほたまちスバル
commands:
  slot:
    description: スロットで遊びます。
    usage: /slot
  roulette:
    description: ルーレットで遊びます。
    usage: /roulette
  blackjack:
    description: ブラックジャックで遊びます。
    usage: /blackjack
  buychips:
    description: チップを買います。
    usage: /buychips <amount>
  casino:
    description: カジノメニューを開きます。
    usage: /casino
  setjackpot:
    description: ジャックポットの値を設定する。
    usage: /setjackpot <amount>
    permission: op
  jackpotrate:
    description: ジャックポットの上昇率を設定する。
    usage: /jackpotrate <rate>
    permission: op

permission:
  casino.jackpot:
    description: ジャックポットの値を設定します。
    usage: /setjackpot <amount>
    permission: casino.jackpot
  casino.jackpot.rate:
    description: ジャックポットの上昇率を設定する。
    usage: /jackpotrate <rate>
    permission: casino.jackpot.rate