name: Casino
version: '1.21.1'
main: net.hotamachisubaru.casino.Casino
api-version: '1.21'
depend:
  - Vault
author:
  Copyright (c) 2024 ほたまちスバル
commands:
  slot:
    description: スロットで遊びます。
    usage: /slot
  roulette:
    description: ルーレットで遊びます。
    usage: /roulette
  blackjack:
    description: ブラックジャックで遊びます。
    usage: /blackjack
  buychips:
    description: チップを買います。
    usage: /buychips <amount>
  casino:
    description: カジノメニューを開きます。
    usage: /casino